	.align 2
gTileset_General::
	.byte TRUE /* is compressed*/
	.byte FALSE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_General
	.int gTilesetPalettes_General
	.int gMetatiles_General
	.int gMetatileAttributes_General
	.int InitTilesetAnim_General

	.align 2
gTileset_Petalburg::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_Petalburg
	.int gTilesetPalettes_Petalburg
	.int gMetatiles_Petalburg
	.int gMetatileAttributes_Petalburg
	.int InitTilesetAnim_Petalburg

	.align 2
gTileset_Rustboro::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_Rustboro
	.int gTilesetPalettes_Rustboro
	.int gMetatiles_Rustboro
	.int gMetatileAttributes_Rustboro
	.int InitTilesetAnim_Rustboro

	.align 2
gTileset_Dewford::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_Dewford
	.int gTilesetPalettes_Dewford
	.int gMetatiles_Dewford
	.int gMetatileAttributes_Dewford
	.int InitTilesetAnim_Dewford

	.align 2
gTileset_Slateport::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_Slateport
	.int gTilesetPalettes_Slateport
	.int gMetatiles_Slateport
	.int gMetatileAttributes_Slateport
	.int InitTilesetAnim_Slateport

	.align 2
gTileset_Mauville::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_Mauville
	.int gTilesetPalettes_Mauville
	.int gMetatiles_Mauville
	.int gMetatileAttributes_Mauville
	.int InitTilesetAnim_Mauville

	.align 2
gTileset_Lavaridge::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_Lavaridge
	.int gTilesetPalettes_Lavaridge
	.int gMetatiles_Lavaridge
	.int gMetatileAttributes_Lavaridge
	.int InitTilesetAnim_Lavaridge

	.align 2
gTileset_Fallarbor::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_Fallarbor
	.int gTilesetPalettes_Fallarbor
	.int gMetatiles_Fallarbor
	.int gMetatileAttributes_Fallarbor
	.int InitTilesetAnim_Fallarbor

	.align 2
gTileset_Fortree::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_Fortree
	.int gTilesetPalettes_Fortree
	.int gMetatiles_Fortree
	.int gMetatileAttributes_Fortree
	.int InitTilesetAnim_Fortree

	.align 2
gTileset_Lilycove::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_Lilycove
	.int gTilesetPalettes_Lilycove
	.int gMetatiles_Lilycove
	.int gMetatileAttributes_Lilycove
	.int InitTilesetAnim_Lilycove

	.align 2
gTileset_Mossdeep::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_Mossdeep
	.int gTilesetPalettes_Mossdeep
	.int gMetatiles_Mossdeep
	.int gMetatileAttributes_Mossdeep
	.int InitTilesetAnim_Mossdeep

	.align 2
gTileset_EverGrande::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_EverGrande
	.int gTilesetPalettes_EverGrande
	.int gMetatiles_EverGrande
	.int gMetatileAttributes_EverGrande
	.int InitTilesetAnim_EverGrande

	.align 2
gTileset_Pacifidlog::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_Pacifidlog
	.int gTilesetPalettes_Pacifidlog
	.int gMetatiles_Pacifidlog
	.int gMetatileAttributes_Pacifidlog
	.int InitTilesetAnim_Pacifidlog

	.align 2
gTileset_Sootopolis::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_Sootopolis
	.int gTilesetPalettes_Sootopolis
	.int gMetatiles_Sootopolis
	.int gMetatileAttributes_Sootopolis
	.int InitTilesetAnim_Sootopolis

	.align 2
gTileset_BattleFrontierOutsideWest::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_BattleFrontierOutsideWest
	.int gTilesetPalettes_BattleFrontierOutsideWest
	.int gMetatiles_BattleFrontierOutsideWest
	.int gMetatileAttributes_BattleFrontierOutsideWest
	.int InitTilesetAnim_BattleFrontierOutsideWest

	.align 2
gTileset_BattleFrontierOutsideEast::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_BattleFrontierOutsideEast
	.int gTilesetPalettes_BattleFrontierOutsideEast
	.int gMetatiles_BattleFrontierOutsideEast
	.int gMetatileAttributes_BattleFrontierOutsideEast
	.int InitTilesetAnim_BattleFrontierOutsideEast

	.align 2
gTileset_Building::
	.byte TRUE /* is compressed*/
	.byte FALSE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_InsideBuilding
	.int gTilesetPalettes_InsideBuilding
	.int gMetatiles_InsideBuilding
	.int gMetatileAttributes_InsideBuilding
	.int InitTilesetAnim_Building

	.align 2
gTileset_Shop::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_Shop
	.int gTilesetPalettes_Shop
	.int gMetatiles_Shop
	.int gMetatileAttributes_Shop
	.int NULL /* animation callback*/

	.align 2
gTileset_PokemonCenter::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_PokemonCenter
	.int gTilesetPalettes_PokemonCenter
	.int gMetatiles_PokemonCenter
	.int gMetatileAttributes_PokemonCenter
	.int NULL /* animation callback*/

	.align 2
gTileset_Cave::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_Cave
	.int gTilesetPalettes_Cave
	.int gMetatiles_Cave
	.int gMetatileAttributes_Cave
	.int InitTilesetAnim_Cave

	.align 2
gTileset_PokemonSchool::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_PokemonSchool
	.int gTilesetPalettes_PokemonSchool
	.int gMetatiles_PokemonSchool
	.int gMetatileAttributes_PokemonSchool
	.int NULL /* animation callback*/

	.align 2
gTileset_PokemonFanClub::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_PokemonFanClub
	.int gTilesetPalettes_PokemonFanClub
	.int gMetatiles_PokemonFanClub
	.int gMetatileAttributes_PokemonFanClub
	.int NULL /* animation callback*/

	.align 2
gTileset_Unused1::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_Unused1
	.int gTilesetPalettes_Unused1
	.int gMetatiles_Unused1
	.int gMetatileAttributes_Unused1
	.int NULL /* animation callback*/

	.align 2
gTileset_MeteorFalls::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_MeteorFalls
	.int gTilesetPalettes_MeteorFalls
	.int gMetatiles_MeteorFalls
	.int gMetatileAttributes_MeteorFalls
	.int NULL /* animation callback*/

	.align 2
gTileset_OceanicMuseum::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_OceanicMuseum
	.int gTilesetPalettes_OceanicMuseum
	.int gMetatiles_OceanicMuseum
	.int gMetatileAttributes_OceanicMuseum
	.int NULL /* animation callback*/

	.align 2
gTileset_CableClub::
	.byte FALSE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_CableClub
	.int gTilesetPalettes_CableClub
	.int gMetatiles_CableClub
	.int gMetatileAttributes_CableClub
	.int NULL /* animation callback*/

	.align 2
gTileset_SeashoreHouse::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_SeashoreHouse
	.int gTilesetPalettes_SeashoreHouse
	.int gMetatiles_SeashoreHouse
	.int gMetatileAttributes_SeashoreHouse
	.int NULL /* animation callback*/

	.align 2
gTileset_PrettyPetalFlowerShop::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_PrettyPetalFlowerShop
	.int gTilesetPalettes_PrettyPetalFlowerShop
	.int gMetatiles_PrettyPetalFlowerShop
	.int gMetatileAttributes_PrettyPetalFlowerShop
	.int NULL /* animation callback*/

	.align 2
gTileset_PokemonDayCare::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_PokemonDayCare
	.int gTilesetPalettes_PokemonDayCare
	.int gMetatiles_PokemonDayCare
	.int gMetatileAttributes_PokemonDayCare
	.int NULL /* animation callback*/

	.align 2
gTileset_Facility::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_Facility
	.int gTilesetPalettes_Facility
	.int gMetatiles_Facility
	.int gMetatileAttributes_Facility
	.int NULL /* animation callback*/

	.align 2
gTileset_BikeShop::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_BikeShop
	.int gTilesetPalettes_BikeShop
	.int gMetatiles_BikeShop
	.int gMetatileAttributes_BikeShop
	.int InitTilesetAnim_BikeShop

	.align 2
gTileset_RusturfTunnel::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_RusturfTunnel
	.int gTilesetPalettes_RusturfTunnel
	.int gMetatiles_RusturfTunnel
	.int gMetatileAttributes_RusturfTunnel
	.int NULL /* animation callback*/

	.align 2
gTileset_SecretBaseBrownCave::
	.byte FALSE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_SecretBaseBrownCave
	.int gTilesetPalettes_SecretBaseBrownCave
	.int gMetatiles_SecretBaseSecondary
	.int gMetatileAttributes_SecretBaseSecondary
	.int NULL /* animation callback*/

	.align 2
gTileset_SecretBaseTree::
	.byte FALSE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_SecretBaseTree
	.int gTilesetPalettes_SecretBaseTree
	.int gMetatiles_SecretBaseSecondary
	.int gMetatileAttributes_SecretBaseSecondary
	.int NULL /* animation callback*/

	.align 2
gTileset_SecretBaseShrub::
	.byte FALSE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_SecretBaseShrub
	.int gTilesetPalettes_SecretBaseShrub
	.int gMetatiles_SecretBaseSecondary
	.int gMetatileAttributes_SecretBaseSecondary
	.int NULL /* animation callback*/

	.align 2
gTileset_SecretBaseBlueCave::
	.byte FALSE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_SecretBaseBlueCave
	.int gTilesetPalettes_SecretBaseBlueCave
	.int gMetatiles_SecretBaseSecondary
	.int gMetatileAttributes_SecretBaseSecondary
	.int NULL /* animation callback*/

	.align 2
gTileset_SecretBaseYellowCave::
	.byte FALSE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_SecretBaseYellowCave
	.int gTilesetPalettes_SecretBaseYellowCave
	.int gMetatiles_SecretBaseSecondary
	.int gMetatileAttributes_SecretBaseSecondary
	.int NULL /* animation callback*/

	.align 2
gTileset_SecretBaseRedCave::
	.byte FALSE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_SecretBaseRedCave
	.int gTilesetPalettes_SecretBaseRedCave
	.int gMetatiles_SecretBaseSecondary
	.int gMetatileAttributes_SecretBaseSecondary
	.int NULL /* animation callback*/

	.align 2
gTileset_InsideOfTruck::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_InsideOfTruck
	.int gTilesetPalettes_InsideOfTruck
	.int gMetatiles_InsideOfTruck
	.int gMetatileAttributes_InsideOfTruck
	.int NULL /* animation callback*/

	.align 2
gTileset_Unused2::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_Unused2
	.int gTilesetPalettes_Unused2
	.int gMetatiles_Unused2
	.int gMetatileAttributes_Unused2
	.int NULL /* animation callback*/

	.align 2
gTileset_Contest::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_Contest
	.int gTilesetPalettes_Contest
	.int gMetatiles_Contest
	.int gMetatileAttributes_Contest
	.int NULL /* animation callback*/

	.align 2
gTileset_LilycoveMuseum::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_LilycoveMuseum
	.int gTilesetPalettes_LilycoveMuseum
	.int gMetatiles_LilycoveMuseum
	.int gMetatileAttributes_LilycoveMuseum
	.int NULL /* animation callback*/

	.align 2
gTileset_BrendansMaysHouse::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_BrendansMaysHouse
	.int gTilesetPalettes_BrendansMaysHouse
	.int gMetatiles_BrendansMaysHouse
	.int gMetatileAttributes_BrendansMaysHouse
	.int NULL /* animation callback*/

	.align 2
gTileset_Lab::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_Lab
	.int gTilesetPalettes_Lab
	.int gMetatiles_Lab
	.int gMetatileAttributes_Lab
	.int NULL /* animation callback*/

	.align 2
gTileset_Underwater::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_Underwater
	.int gTilesetPalettes_Underwater
	.int gMetatiles_Underwater
	.int gMetatileAttributes_Underwater
	.int InitTilesetAnim_Underwater

	.align 2
gTileset_PetalburgGym::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_PetalburgGym
	.int gTilesetPalettes_PetalburgGym
	.int gMetatiles_PetalburgGym
	.int gMetatileAttributes_PetalburgGym
	.int NULL /* animation callback*/

	.align 2
gTileset_SootopolisGym::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_SootopolisGym
	.int gTilesetPalettes_SootopolisGym
	.int gMetatiles_SootopolisGym
	.int gMetatileAttributes_SootopolisGym
	.int InitTilesetAnim_SootopolisGym

	.align 2
gTileset_GenericBuilding::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_GenericBuilding
	.int gTilesetPalettes_GenericBuilding
	.int gMetatiles_GenericBuilding
	.int gMetatileAttributes_GenericBuilding
	.int NULL /* animation callback*/

	.align 2
gTileset_MauvilleGameCorner::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_MauvilleGameCorner
	.int gTilesetPalettes_MauvilleGameCorner
	.int gMetatiles_MauvilleGameCorner
	.int gMetatileAttributes_MauvilleGameCorner
	.int NULL /* animation callback*/

	.align 2
gTileset_RustboroGym::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_RustboroGym
	.int gTilesetPalettes_RustboroGym
	.int gMetatiles_RustboroGym
	.int gMetatileAttributes_RustboroGym
	.int NULL /* animation callback*/

	.align 2
gTileset_DewfordGym::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_DewfordGym
	.int gTilesetPalettes_DewfordGym
	.int gMetatiles_DewfordGym
	.int gMetatileAttributes_DewfordGym
	.int NULL /* animation callback*/

	.align 2
gTileset_MauvilleGym::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_MauvilleGym
	.int gTilesetPalettes_MauvilleGym
	.int gMetatiles_MauvilleGym
	.int gMetatileAttributes_MauvilleGym
	.int InitTilesetAnim_MauvilleGym

	.align 2
gTileset_LavaridgeGym::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_LavaridgeGym
	.int gTilesetPalettes_LavaridgeGym
	.int gMetatiles_LavaridgeGym
	.int gMetatileAttributes_LavaridgeGym
	.int NULL /* animation callback*/

	.align 2
gTileset_TrickHousePuzzle::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_TrickHousePuzzle
	.int gTilesetPalettes_TrickHousePuzzle
	.int gMetatiles_TrickHousePuzzle
	.int gMetatileAttributes_TrickHousePuzzle
	.int NULL /* animation callback*/

	.align 2
gTileset_FortreeGym::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_FortreeGym
	.int gTilesetPalettes_FortreeGym
	.int gMetatiles_FortreeGym
	.int gMetatileAttributes_FortreeGym
	.int NULL /* animation callback*/

	.align 2
gTileset_MossdeepGym::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_MossdeepGym
	.int gTilesetPalettes_MossdeepGym
	.int gMetatiles_MossdeepGym
	.int gMetatileAttributes_MossdeepGym
	.int NULL /* animation callback*/

	.align 2
gTileset_InsideShip::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_InsideShip
	.int gTilesetPalettes_InsideShip
	.int gMetatiles_InsideShip
	.int gMetatileAttributes_InsideShip
	.int NULL /* animation callback*/

	.align 2
gTileset_SecretBase::
	.byte FALSE /* is compressed*/
	.byte FALSE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_SecretBase
	.int gTilesetPalettes_SecretBase
	.int gMetatiles_SecretBasePrimary
	.int gMetatileAttributes_SecretBasePrimary
	.int NULL /* animation callback*/

	.align 2
gTilesetPointer_SecretBase::
	.int gTileset_SecretBase

	.align 2
gTilesetPointer_SecretBaseRedCave::
	.int gTileset_SecretBaseRedCave

	.align 2
gTileset_EliteFour::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_EliteFour
	.int gTilesetPalettes_EliteFour
	.int gMetatiles_EliteFour
	.int gMetatileAttributes_EliteFour
	.int InitTilesetAnim_EliteFour

	.align 2
gTileset_BattleFrontier::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_BattleFrontier
	.int gTilesetPalettes_BattleFrontier
	.int gMetatiles_BattleFrontier
	.int gMetatileAttributes_BattleFrontier
	.int NULL /* animation callback*/

	.align 2
gTileset_BattlePalace::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_BattlePalace
	.int gTilesetPalettes_BattlePalace
	.int gMetatiles_BattlePalace
	.int gMetatileAttributes_BattlePalace
	.int NULL /* animation callback*/

	.align 2
gTileset_BattleDome::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_BattleDome
	.int gTilesetPalettes_BattleDome
	.int gMetatiles_BattleDome
	.int gMetatileAttributes_BattleDome
	.int InitTilesetAnim_BattleDome

	.align 2
gTileset_BattleFactory::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_BattleFactory
	.int gTilesetPalettes_BattleFactory
	.int gMetatiles_BattleFactory
	.int gMetatileAttributes_BattleFactory
	.int NULL /* animation callback*/

	.align 2
gTileset_BattlePike::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_BattlePike
	.int gTilesetPalettes_BattlePike
	.int gMetatiles_BattlePike
	.int gMetatileAttributes_BattlePike
	.int NULL /* animation callback*/

	.align 2
gTileset_BattleArena::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_BattleArena
	.int gTilesetPalettes_BattleArena
	.int gMetatiles_BattleArena
	.int gMetatileAttributes_BattleArena
	.int NULL /* animation callback*/

	.align 2
gTileset_BattlePyramid::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_BattlePyramid
	.int gTilesetPalettes_BattlePyramid
	.int gMetatiles_BattlePyramid
	.int gMetatileAttributes_BattlePyramid
	.int InitTilesetAnim_BattlePyramid

	.align 2
gTileset_MirageTower::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_MirageTower
	.int gTilesetPalettes_MirageTower
	.int gMetatiles_MirageTower
	.int gMetatileAttributes_MirageTower
	.int NULL /* animation callback*/

	.align 2
gTileset_MossdeepGameCorner::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_MossdeepGameCorner
	.int gTilesetPalettes_MossdeepGameCorner
	.int gMetatiles_MossdeepGameCorner
	.int gMetatileAttributes_MossdeepGameCorner
	.int NULL /* animation callback*/

	.align 2
gTileset_IslandHarbor::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_IslandHarbor
	.int gTilesetPalettes_IslandHarbor
	.int gMetatiles_IslandHarbor
	.int gMetatileAttributes_IslandHarbor
	.int NULL /* animation callback*/

	.align 2
gTileset_TrainerHill::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_TrainerHill
	.int gTilesetPalettes_TrainerHill
	.int gMetatiles_TrainerHill
	.int gMetatileAttributes_TrainerHill
	.int NULL /* animation callback*/

	.align 2
gTileset_NavelRock::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_NavelRock
	.int gTilesetPalettes_NavelRock
	.int gMetatiles_NavelRock
	.int gMetatileAttributes_NavelRock
	.int NULL /* animation callback*/

	.align 2
gTileset_BattleFrontierRankingHall::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_BattleFrontierRankingHall
	.int gTilesetPalettes_BattleFrontierRankingHall
	.int gMetatiles_BattleFrontierRankingHall
	.int gMetatileAttributes_BattleFrontierRankingHall
	.int NULL /* animation callback*/

	.align 2
gTileset_BattleTent::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_BattleTent
	.int gTilesetPalettes_BattleTent
	.int gMetatiles_BattleTent
	.int gMetatileAttributes_BattleTent
	.int NULL /* animation callback*/

	.align 2
gTileset_MysteryEventsHouse::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_MysteryEventsHouse
	.int gTilesetPalettes_MysteryEventsHouse
	.int gMetatiles_MysteryEventsHouse
	.int gMetatileAttributes_MysteryEventsHouse
	.int NULL /* animation callback*/

	.align 2
gTileset_UnionRoom::
	.byte TRUE /* is compressed*/
	.byte TRUE /* is secondary tileset*/
	.short 0 /* padding*/
	.int gTilesetTiles_UnionRoom
	.int gTilesetPalettes_UnionRoom
	.int gMetatiles_UnionRoom
	.int gMetatileAttributes_UnionRoom
	.int NULL /* animation callback*/
